services:
  - type: web
    name: health-monitor-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: MONGO_URI
        value: <mongodb+srv://mushabbirahmed99:LIofUe11vs3pvn4I@cluster0.vsiadwx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0>
