services:
  - type: web
    name: health-monitor-backend
    env: python
    buildCommand: ""  # No build needed for Flask
    startCommand: "python app.py"
    workingDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: MONGO_URI
        value: mongodb+srv://mushabbirahmed99:LIofUe11vs3pvn4I@cluster0.vsiadwx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
